# Add useful directories to path
export PATH="$HOME/scripts:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$HOME/.nix-profile/bin:$PATH"
if command -v ghcup > /dev/null; then
    export PATH="$(ghcup whereis bindir):$PATH"
fi

# Set EDITOR to Emacs client or Neovim if available, otherwise vi
if systemctl --user is-active emacs > /dev/null; then
    export EDITOR='emacsclient -nw'
elif command -v nvim > /dev/null; then
    export EDITOR=nvim
else
    export EDITOR=vi
fi

# Useful aliases
alias ec='emacsclient -nw'
alias sxiv='sxiv -a'
alias sudo='sudo -E'
alias ip='ip -c'
alias wine32='WINEARCH=win32 WINEPREFIX=~/.wine32 wine'
alias mkvenv='mkvirtualenv `basename $PWD`'
alias rmvenv='rmvirtualenv `basename $PWD`'

# Set up Node Version Manager
if [ -f /usr/share/nvm/init-nvm.sh ]; then
    source /usr/share/nvm/init-nvm.sh
fi

# Needed for YubiKey + ssh
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# Load extra config
if [ -f "$HOME/.zshrc.extra" ]; then
    source "$HOME/.zshrc.extra"
fi

{%@@ if profile == 'atuin' @@%}
export REM_LAMBDA_KUBERNETES=1
{%@@ endif @@%}

# Oh My Zsh
export ZSH="$HOME/.config/oh-my-zsh"
ZSH_THEME=rem-lambda
ENABLE_CORRECTION="false"
plugins=(
    direnv
    docker
    docker-compose
    fzf
    git
    kubectl
    pip
    shrink-path
    virtualenvwrapper
    zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh
