# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=rem-lambda
ENABLE_CORRECTION="true"
plugins=(
    git
    docker
    docker-compose
    kubectl
    pip
    virtualenvwrapper
    zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh

# Add useful directories to path
export PATH="$HOME/scripts:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Set EDITOR to neovim if it's installed
if command -v nvim > /dev/null
then
    export EDITOR=nvim
fi

# Useful aliases
alias sxiv='sxiv -a'
alias sudo='sudo -E'
alias ip='ip -c'
alias wine32='WINEARCH=win32 WINEPREFIX=~/.wine32 wine'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gdc='git diff --cached'
alias go='git checkout'
alias gh='git hist'
alias gp='git pull'
alias gu='git push'
alias gm='git merge'
alias gl='git log'

# Set up virtualenvwrapper
if [ -f /usr/bin/virtualenvwrapper.sh ]
then
    export WORKON_HOME=~/.virtualenvs
    source /usr/bin/virtualenvwrapper.sh
fi

# Needed for YubiKey + ssh
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
