# Oh My Zsh
export ZSH="$HOME/.config/oh-my-zsh"
ZSH_THEME=rem-lambda
ENABLE_CORRECTION="false"
plugins=(
    git
    docker
    docker-compose
    kubectl
    pip
    virtualenvwrapper
    shrink-path
    direnv
    fzf
)
# Suggestion colors don't work properly in emacs term
if [ $TERM != "eterm-color" ]
then
    plugins+=(zsh-autosuggestions)
fi
source $ZSH/oh-my-zsh.sh

{%@@ if colorscheme == "solarized-dark" @@%}
# zsh-autosuggestion isn't visible with solarized dark
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'
{%@@ endif @@%}

# Add useful directories to path
export PATH="$HOME/scripts:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
if command -v ghcup > /dev/null
then
    export PATH="$(ghcup whereis bindir):$PATH"
fi

# Set EDITOR to neovim if it's installed
if command -v nvim > /dev/null
then
    export EDITOR=nvim
fi

# Useful aliases
alias sxiv='sxiv -a'
alias sudo='sudo -E'
alias ip='ip -c'
alias wine32='WINEARCH=win32 WINEPREFIX=~/.wine32 wine'

# Set up Node Version Manager
if [ -f /usr/share/nvm/init-nvm.sh ]
then
    source /usr/share/nvm/init-nvm.sh
fi

# Needed for YubiKey + ssh
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# Load extra config
if [ -f "$HOME/.zshrc.extra" ]
then
    source "$HOME/.zshrc.extra"
fi
