config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
variables:
  distro: arch
  colorscheme: solarized-dark
  terminal: alacritty
  browser: firefox
actions:
  pre:
    vim-plug-install: test -e ~/.config/nvim/autoload/plug.vim || (mkdir -p ~/.config/nvim/autoload;
      curl -fLo ~/.config/nvim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
    vim-folders: mkdir -p ~/.config/nvim/undo ~/.config/nvim/swap ~/.config/nvim/backup
  vim-plug: nvim +PlugInstall +qall
  oh-my-zsh: test -e ~/.config/oh-my-zsh || (git clone https://github.com/robbyrussell/oh-my-zsh.git
    ~/.config/oh-my-zsh)
  zsh-autosuggestions: test -e ~/.config/oh-my-zsh/custom/plugins/zsh-autosuggestions
    || (git clone https://github.com/zsh-users/zsh-autosuggestions ~/.config/oh-my-zsh/custom/plugins/zsh-autosuggestions)
dotfiles:
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_xresources-include:
    src: Xresources-include
    dst: ~/.Xresources-include
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_mpd:
    src: config/mpd
    dst: ~/.config/mpd
    ignore_missing_in_dotdrop: true
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    actions:
    - vim-plug-install
    - vim-plug
    - vim-folders
    cmpignore:
    - autoload/plug.vim
    - plugged
    - backup
    - swap
    - undo
    upignore:
    - autoload/plug.vim
    - plugged
    - backup
    - swap
    - undo
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_redshift:
    src: config/redshift
    dst: ~/.config/redshift
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  f_eslintrc:
    src: eslintrc
    dst: ~/.eslintrc
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    instignore:
    - colors
  d_ncmpcpp:
    src: config/ncmpcpp
    dst: ~/.config/ncmpcpp
    cmpignore:
    - error.log
    upignore:
    - error.log
  f_stylelintrc:
    src: stylelintrc
    dst: ~/.stylelintrc
  d_weechat:
    src: weechat
    dst: ~/.weechat
    ignore_missing_in_dotdrop: true
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    actions:
    - oh-my-zsh
    - zsh-autosuggestions
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  f_rem-lambda.zsh-theme:
    src: config/oh-my-zsh/custom/themes/rem-lambda.zsh-theme
    dst: ~/.config/oh-my-zsh/custom/themes/rem-lambda.zsh-theme
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  d_emacs:
    src: config/emacs
    dst: ~/.config/emacs
    chmod: '700'
    ignore_missing_in_dotdrop: true
  d_git:
    src: config/git
    dst: ~/.config/git
    cmpignore:
    - user
    upignore:
    - user
profiles:
  athena:
    variables:
      colorscheme: gruvbox-dark
    dotfiles:
    - f_xresources
    - d_xresources-include
    - d_alacritty
    - d_dunst
    - d_kitty
    - d_mpd
    - d_nvim
    - d_picom
    - d_polybar
    - d_ranger
    - d_redshift
    - d_sway
    - d_waybar
    - d_zathura
    - f_eslintrc
    - d_git
    - d_i3
    - d_ncmpcpp
    - f_stylelintrc
    - d_weechat
    - f_zshrc
    - f_rem-lambda.zsh-theme
    - d_rofi
    - d_fontconfig
    - d_emacs
  helios:
    variables:
      colorscheme: dracula
      browser: firefox-developer-edition
    dotfiles:
    - f_xresources
    - d_xresources-include
    - d_alacritty
    - d_dunst
    - d_kitty
    - d_mpd
    - d_nvim
    - d_picom
    - d_polybar
    - d_ranger
    - d_redshift
    - d_zathura
    - f_eslintrc
    - d_git
    - d_i3
    - d_ncmpcpp
    - f_stylelintrc
    - d_weechat
    - f_zshrc
    - f_rem-lambda.zsh-theme
    - d_rofi
    - d_fontconfig
    - d_emacs
  dev-pc-28:
    variables:
      colorscheme: gruvbox-dark
    dotfiles:
    - f_xresources
    - d_xresources-include
    - d_alacritty
    - d_dunst
    - d_nvim
    - d_picom
    - d_polybar
    - d_ranger
    - d_zathura
    - d_git
    - d_i3
    - f_zshrc
    - f_rem-lambda.zsh-theme
    - d_rofi
    - d_fontconfig
    - d_emacs
