[
  ./alacritty
  ./autorandr.nix
  ./common.nix
  ./dunst.nix
  ./emacs
  ./fonts.nix
  ./git.nix
  ./gtk.nix
  ./i3
  ./mpd.nix
  ./nixgl.nix
  ./nodejs.nix
  ./packages.nix
  ./picom.nix
  ./polybar
  ./rofi
  ./touchpad.nix
  ./zathura.nix
  ./zsh.nix
] ++ (if builtins.pathExists ./local.nix then [ ./local.nix ] else [ ])
