{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-generate-config
  ] ++ import ./../../modules/system;

  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
    initrd.kernelModules = [ "dm-snapshot" ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    # ^------------------------------------^

    loader.efi.canTouchEfiVariables = true;
    # We need to use grub for luks support
    loader.grub = {
      enable = true;
      device = "nodev";
      efiSupport = true;
      enableCryptodisk = true;
    };
    loader.efi.efiSysMountPoint = "/boot/efi";
    # Thanks to this keyfile we don't need to enter the luks password twice
    # https://wiki.archlinux.org/title/Dm-crypt/Device_encryption#With_a_keyfile_embedded_in_the_initramfs
    initrd.secrets = {
      "/crypto_keyfile.bin" = "/root/secrets/crypto_keyfile.bin";
    };
    initrd.luks.devices = {
      root = {
        device = "/dev/disk/by-uuid/170faa4b-61ec-4f4a-ad31-9ccd58eeff6a";
        keyFile = "/crypto_keyfile.bin";
        preLVM = true;
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/6c757c81-2bf8-4105-8dc9-732111d27e0e";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/6c757c81-2bf8-4105-8dc9-732111d27e0e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/6c757c81-2bf8-4105-8dc9-732111d27e0e";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" ];
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/71D4-5033";
      fsType = "vfat";
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e20fce16-944a-4a7d-aea1-2ac786462a62"; }
  ];

  networking.hostName = "atuin";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # User setup
  users.groups.vojta = {
    gid = 1000;
  };
  users.users.vojta = {
    uid = 1000;
    group = "vojta";
    isNormalUser = true;
    description = "Vojtěch Balák";
    extraGroups = [ "networkmanager" "wheel" "docker" "libvirt" "scanner" "lp" ];
    shell = pkgs.zsh;
  };
  programs._1password-gui.polkitPolicyOwners = [ "vojta" ];

  services.openssh.enable = true;
}
