{ config, lib, pkgs, ... }:
{
  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
    initrd.kernelModules = [ "dm-snapshot" ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    # ^------------------------------------^
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/6c757c81-2bf8-4105-8dc9-732111d27e0e";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/6c757c81-2bf8-4105-8dc9-732111d27e0e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/6c757c81-2bf8-4105-8dc9-732111d27e0e";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" ];
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/71D4-5033";
      fsType = "vfat";
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e20fce16-944a-4a7d-aea1-2ac786462a62"; }
  ];

  system-modules = {
    common = {
      userName = "vojta";
      hostName = "atuin";
      cpuType = "intel";
    };
    boot.luks = {
      enable = true;
      uuid = "170faa4b-61ec-4f4a-ad31-9ccd58eeff6a";
    };
    nix-ld.enable = true;
  };
}
