db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"

playlist_directory "~/.config/mpd/playlists"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

{%@@ if profile == "athena" @@%}
music_directory    "/media/data/Dokumenty/audio"
{%@@ elif profile == "helios" @@%}
music_directory    "~/Network/Media/Audio"
{%@@ else @@%}
music_directory    "~/Music"
{%@@ endif @@%}

bind_to_address "127.0.0.1"

audio_output {
    type    "pipewire"
    name    "PipeWire Sound Server"
}

audio_output {
    type    "fifo"
    name    "my_fifo"
    path    "/tmp/mpd.fifo"
    format  "44100:16:2"
}
