{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    # ^------------------------------------^
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/4e6fcc6a-8dce-46e1-8b99-e174f0fe792c";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/4e6fcc6a-8dce-46e1-8b99-e174f0fe792c";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/4e6fcc6a-8dce-46e1-8b99-e174f0fe792c";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/FFEE-5BF3";
      fsType = "vfat";
    };

  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/9d0eff90-fd15-40ea-a080-c8301a207307"; }
  ];

  # Qemu guest integration
  services.qemuGuest.enable = true;
  services.spice-vdagentd.enable = true;

  system-modules = {
    common = {
      userName = "remedan";
      hostName = "nixos";
      cpuType = "amd";
    };
    nix-ld.enable = true;
  };
}
