cursor #93a1a1

#: Default cursor color

cursor_text_color #002b36

#: Choose the color of text under the cursor. If you want it rendered
#: with the background color of the cell underneath instead, use the
#: special keyword: background

foreground #839496
background #002b36

#: The foreground and background colors

selection_foreground #000000

#: The foreground for text selected with the mouse. A value of none
#: means to leave the color unchanged.

selection_background #fffacd

#: The background for text selected with the mouse.

#: The 16 terminal colors. There are 8 basic colors, each color has a
#: dull and bright version. You can also set the remaining colors from
#: the 256 color table as color16 to color255.

color0 #073642
color8 #002b36

#: black

color1 #dc322f
color9 #cb4b16

#: red

color2  #859900
color10 #586e75

#: green

color3  #b58900
color11 #657b83

#: yellow

color4  #268bd2
color12 #839496

#: blue

color5  #d33682
color13 #6c71c4

#: magenta

color6  #2aa198
color14 #93a1a1

#: cyan

color7  #eee8d5
color15 #fdf6e3

#: white
