{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-generate-config
  ];

  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    # ^------------------------------------^

    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;

    # Fixes Xbox controller pairing
    extraModprobeConfig = '' options bluetooth disable_ertm=1 '';
  };

  fileSystems =
    let
      cifsOptions = [
        "_netdev"
        "nofail"
        "vers=2.1"
        "credentials=/home/remedan/.smbcredentials"
        "uid=${toString config.users.users.remedan.uid}"
        "gid=${toString config.users.groups.remedan.gid}"
      ];
    in
    {
      "/" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@" ];
      };

      "/nix" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@nix" "noatime" ];
      };

      "/home" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@home" ];
      };

      "/boot" = {
        device = "/dev/disk/by-uuid/EE81-37E8";
        fsType = "vfat";
      };

      "/home/remedan/Network/home" = {
        device = "//192.168.4.3/homes/remedan";
        fsType = "cifs";
        options = cifsOptions;
      };

      "/home/remedan/Network/Media" = {
        device = "//192.168.4.3/Media";
        fsType = "cifs";
        options = cifsOptions;
      };
    };

  swapDevices = [
    { device = "/dev/disk/by-uuid/8fb1f7ff-4f1a-42c4-bc30-567e976c7a54"; }
    { device = "/dev/disk/by-uuid/589f663d-8784-4e17-9634-829edb852c59"; }
  ];

  networking = {
    useDHCP = lib.mkDefault true;
    hostName = "weatherwax";
    networkmanager.enable = true;
  };

  time.timeZone = "Europe/Prague";

  # Set language to English but formats to Czech
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "cs_CZ.UTF-8";
    LC_IDENTIFICATION = "cs_CZ.UTF-8";
    LC_MEASUREMENT = "cs_CZ.UTF-8";
    LC_MONETARY = "cs_CZ.UTF-8";
    LC_NAME = "cs_CZ.UTF-8";
    LC_NUMERIC = "cs_CZ.UTF-8";
    LC_PAPER = "cs_CZ.UTF-8";
    LC_TELEPHONE = "cs_CZ.UTF-8";
    LC_TIME = "cs_CZ.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    displayManager.gdm.enable = true;
    desktopManager.gnome.enable = true;
    windowManager.i3.enable = true;

    # Configure keymap in X11
    layout = "us";
    xkbVariant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  sound.enable = true;
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };


  # Nvidia setup
  # Taken from https://nixos.wiki/wiki/Nvidia#Modifying_NixOS_Configuration

  # Enable OpenGL
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    # Modesetting is required.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    powerManagement.enable = false;
    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    open = false;

    # Enable the Nvidia settings menu,
    # accessible via `nvidia-settings`.
    nvidiaSettings = true;

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # Update CPU microcode
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable bluetooth
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  services.blueman.enable = true;

  # User setup
  users.groups.remedan = {
    gid = 1000;
  };
  users.users.remedan = {
    uid = 1000;
    group = "remedan";
    isNormalUser = true;
    description = "Vojta";
    extraGroups = [ "networkmanager" "wheel" "docker" "libvirt" ];
    shell = pkgs.zsh;
  };

  environment.systemPackages = with pkgs; [
    vim
    wget
    git
    cifs-utils
    virt-manager
  ];

  programs.zsh.enable = true;
  programs._1password.enable = true;
  programs._1password-gui.enable = true;
  programs._1password-gui.polkitPolicyOwners = [ "remedan" ];
  programs.steam.enable = true;

  services.openssh.enable = true;

  services.tailscale.enable = true;

  virtualisation.docker = {
    enable = true;
    storageDriver = "btrfs";
  };
  virtualisation.libvirtd.enable = true;

  # Polkit
  security.polkit.enable = true;
  # Enable authentication agent since i3 doesn't start it
  # Taken from https://nixos.wiki/wiki/Polkit#Authentication_agents
  systemd.user.services.polkit-gnome-authentication-agent-1 = {
    description = "polkit-gnome-authentication-agent-1";
    wantedBy = [ "graphical-session.target" ];
    wants = [ "graphical-session.target" ];
    after = [ "graphical-session.target" ];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
      Restart = "on-failure";
      RestartSec = 1;
      TimeoutStopSec = 10;
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  nixpkgs.config.allowUnfree = true;

  system.stateVersion = "23.11"; # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
}
