{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-generate-config
  ] ++ import ./../../modules/system;

  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    # ^------------------------------------^

    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;

    # Fixes Xbox controller pairing
    extraModprobeConfig = '' options bluetooth disable_ertm=1 '';
  };

  fileSystems =
    let
      cifsOptions = [
        "_netdev"
        "nofail"
        "vers=2.1"
        "credentials=/home/remedan/.smbcredentials"
        "uid=${toString config.users.users.remedan.uid}"
        "gid=${toString config.users.groups.remedan.gid}"
      ];
    in
    {
      "/" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@" ];
      };

      "/nix" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@nix" "noatime" ];
      };

      "/home" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@home" ];
      };

      "/boot" = {
        device = "/dev/disk/by-uuid/EE81-37E8";
        fsType = "vfat";
      };

      "/home/remedan/Network/home" = {
        device = "//192.168.4.3/homes/remedan";
        fsType = "cifs";
        options = cifsOptions;
      };

      "/home/remedan/Network/Media" = {
        device = "//192.168.4.3/Media";
        fsType = "cifs";
        options = cifsOptions;
      };
    };

  swapDevices = [
    { device = "/dev/disk/by-uuid/8fb1f7ff-4f1a-42c4-bc30-567e976c7a54"; }
    { device = "/dev/disk/by-uuid/589f663d-8784-4e17-9634-829edb852c59"; }
  ];

  # Update CPU microcode
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Nvidia setup
  # Taken from https://nixos.wiki/wiki/Nvidia#Modifying_NixOS_Configuration

  # Enable OpenGL
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  # Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    # Modesetting is required.
    modesetting.enable = true;

    # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
    powerManagement.enable = false;
    # Fine-grained power management. Turns off GPU when not in use.
    # Experimental and only works on modern Nvidia GPUs (Turing or newer).
    powerManagement.finegrained = false;

    # Use the NVidia open source kernel module (not to be confused with the
    # independent third-party "nouveau" open source driver).
    open = false;

    # Enable the Nvidia settings menu,
    # accessible via `nvidia-settings`.
    nvidiaSettings = true;

    # Optionally, you may need to select the appropriate driver version for your specific GPU.
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  system-modules.common = {
    userName = "remedan";
    hostName = "weatherwax";
  };

  programs.steam.enable = true;

  services.openssh.enable = true;
  services.tailscale.enable = true;
  services.flatpak.enable = true;
}
